name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.0
  intl: any
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  intl_utils: any

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - lib/l10n/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
